name: netflix_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
 
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  share_plus: ^10.1.4
  video_player: ^2.9.5
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  bordered_text: ^2.0.0

  flutter_native_splash: ^2.4.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 

flutter_native_splash:
  android_gravity: center
  color: "#ffffff"  
  image: assets/icons/launcher_logo.png 
  color_dark: "#000000"  
  image_dark: assets/icons/launcher_logo.png
  android_12:
    color: "#ffffff"  
    image: assets/icons/launcher_logo.png
    color_dark: "#000000"  
    image_dark: assets/icons/launcher_logo.png

  ios: true 
  web: false
 
flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/

 