name: netflix_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  bordered_text: ^2.0.0

  # State Management & DI
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Functional & Serialization
  dartz: ^0.10.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Media & Sharing
  video_player: ^2.9.5
  share_plus: ^10.1.4

  # Dev Tools
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  flutter_oss_licenses: ^3.0.4
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  injectable_generator: ^2.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  android_gravity: center
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/icons/launcher_logo.png
  image_dark: assets/icons/launcher_logo.png
  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: assets/icons/launcher_logo.png
    image_dark: assets/icons/launcher_logo.png
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/licenses/
    - assets/readme/
